dataset_name: lego
dataset_path: nerf_synthetic/lego
dataset_type: lego 


near: 2.
far: 6.

scale: 0.4
num_samples_coarse: 64 
num_samples_fine: 128 
use_hvs: True 
L_position: 10 
L_direction: 4 

num_epochs: 20_000
learning_rate: 5.e-4
optimizer: adam
batch_size: 1024 
num_devices: 1
steps_per_eval: 2000

ckpt_dir: 'ckpt_lego_dir'
load_ckpt_dir: 'ckpt_lego_dir'

