dataset_name: lego
dataset_path: nerf_synthetic/lego
dataset_type: lego 


near: 2.
far: 6.

scale: 0.125
num_samples_coarse: 64 
num_samples_fine: 128 
use_hvs: True 
L_position: 10 
L_direction: 4 

num_epochs: 500000000
learning_rate: 5.e-5
optimizer: adam

ckpt_dir: 'ckpt_lego_dir'



